### PR TITLE
Do some safe cleanup of two files

### PR DESCRIPTION
**Pull request by dcbriccetti**
Do some safe cleanup of two files before working on them: Remove valueless comments. Simplify comments. Add @Override annotation. Use new-style “for”. Remove explicit boxing and unboxing. Use addAll instead of a loop with add. Combine identical catch clauses. Format lines.

#### What has been done to verify that this works as intended?
Ran tests.

#### Are there any risks to merging this code? If so, what are they?
Problems are unlikely, as IDEA made all the changes other than those to comments.

### CODE REVIEW

**Comment by dcbriccetti** [comment]
Wow, did everyone know about adding ?w=1 to ignore whitespace changes‽

https://github.com/opendatakit/javarosa/pull/184/commits/0eea636250c5cef57d773dd13a1f13b53c0fc5b7?w=1

**Comment by lognaturel** [comment]
I did not, thank you‽‽

**Comment by dcbriccetti** [comment]
@opendatakit-bot, please flag that illegal use of interrobang! ;-)

**Comment by lognaturel** [comment]
Haha!

**Pull request merged**
