### PR TITLE
Switch to AdoptOpenJDK for license compliance

### LINKED ISSUE #487: Build JavaRosa with OpenJDK and update the readme

### PR DESCRIPTION
**Pull request by yanokwa**
Closes #487. We should issue a point release with this change.

### CODE REVIEW

**Comment by ggalmazor** [comment]
Just curious why AdoptOpenJDK and not Java.net's OpenJDK (or any other vendor)? Can we be less specific and just say OpenJDK 8.0.221?

Also, I think we should specify the full version needed (we know that a lower patch version of Java8 won't work well with cryptography).

-- 

So, just to have a full picture of what we're doing in other tools:

- The releases of Aggregate and JavaRosa that I've released so far, have been built with Oracle's Java8u201.
- Briefcase is being released with Java.net's OpenJDK 11.0.2 release.

**Comment by yanokwa** [comment]
AdoptOpenJDK because https://openjdk.java.net only seems to have Java 12 binaries. The rest are either reference implementations for some, but not all OSes. https://adoptopenjdk.net has JDK 8, 11, and 12 and for all OSes. Seems way more straightforward for users.

Totally OK specifying the full version. Could we say "We recommend OpenJDK 11, but OpenJDK 8.0.221 or greater should work".

I think to be totally safe as far as licensing, we should build all future releases with OpenJDK. Does that seem possible/reasonable?

**Comment by yanokwa** [comment]
@lognaturel and I discussed this with @ggalmazor and the agreement here is that we will build with Adopt OpenJDK, and we should suggest users run Adopt OpenJDK, but developers can use whatever OpenJDK that they want. 

Adopt OpenJDK has patches that are in Oracle Java but not in Java.net's OpenJDK. But because Adopt OpenJDK is easier to well, adopt, we are using it. It might be slightly risky because of aforementioned patches, but it's a widely-used JDK.

**Comment by lognaturel** [comment]
> The releases of Aggregate and JavaRosa that I've released so far, have been built with Oracle's Java8u201.

And to be explicit, this is totally fine because Java8u201 came before Oracle's licensing requirements.

**Pull request merged**
