### PR TITLE
Add support for range control #39

### PR DESCRIPTION
**Pull request by dcbriccetti**
Work in progress. Built on the 25-modernize-xformparser branch. The key change is this commit: https://github.com/dcbriccetti/javarosa/commit/a099ca7a927b9051c39b38a97ad40e3c4a1d6a26. There is some prep work earlier in the day, Apr 26.

### CODE REVIEW

**Comment by dcbriccetti** [comment]
@lognaturel, @mitchellsundt and @ctsims, perhaps you’ll have a moment to look over this change. https://github.com/opendatakit/javarosa/pull/44/commits/3911f907b9b8381638df4cf36892069a78134813
Thanks!

**Comment by dcbriccetti** [comment]
Hi @lognaturel. I was hoping for some reassurance from @mitchellsundt and/or @ctsims, but if you like the tests and the implementation, I say this is ready to go.

**Comment by ctsims** [comment]
This implementation makes sense to me and seems quite clean. I appreciate the lack of appearance attributes full of magic strings :p.

**Comment by dcbriccetti** [comment]
@ctsims, thanks for having a look!

**Comment by lognaturel** [comment]
@ctsims Thanks so much for the reassurance as we get our JavaRosa sea legs!! And @dcbriccetti thanks for the clean implementation. Yay for `BigDecimal`! 😄

**Pull request merged**
