### PR TITLE
Round problem, Issue #5

### PR DESCRIPTION
**Pull request by dcbriccetti**
This branch is off of `abs-function`. The changes for Issue #5 start at “Use assertEquals ...”.

See Issue #5 for discussion.

### CODE REVIEW

**Comment by dcbriccetti** [comment]
This is ready to merge. It might be good to merge it now—it has improved tests—and then discuss in the issue what to do from here.

**Comment by lognaturel** [comment]
Hmm, the #32 merge caused some conflicts.

**Comment by dcbriccetti** [comment]
Sorry. Looks right now.

**Comment by lognaturel** [comment]
Was going to merge this but I have pondered and I think we should see if the fix can come in this branch too. Would be nice to group them together!

**Comment by dcbriccetti** [comment]
OK, this is ready if you agree with the solution.

**Pull request merged**
