### PR TITLE
Converting TextFormTests to Junit4

### PR DESCRIPTION
**Pull request by macdude357**
I converted one of the tests to use annotations.  It seemed like the use of Suites isn't really necessary with JUnit4, so I removed that.  I'd like to get feedback on this before migrating the other tests.
@ggalmazor

### CODE REVIEW

**Comment by ggalmazor** [comment]
Hi, @macdude357!

I wanted to share with you the next steps in our effort of improving the test suite and JR in general so that you can know how the big picture looks like on this front. I guess this information really applies to anyone contributing to JR too:

- Step 1: Migrate everything to junit4 (this PR)
- Step 2: Migrate tests to the `Scenario` class where it makes sense
- Step 3: Migrate tests to the `XFormsElement` form building DSL where it makes sense

As you know, we're embarking on a journey to improve JR and make it more reliable and performant, but we can't do it without the support of a good toolset. We believe that `Scenario` and `XFormsElement` represent how some part of that toolset should look like but they're in very early stages. That's why we need to have more people using them so that we can detect all their friction points, flaws and shortcomings so that we can improve them too along the way.

The `Scenario` class should help describing JR's high-level behavior by letting test writers describe an interaction workflow with a form and assertions based on the values in the form submission.

The `XFormsElement` class provides a DSL to build XForms documents. This DSL should provide a programmatic API that has a one-to-one relationship with what the XForms specs say. I gave more context about the DSL in another comment at https://github.com/opendatakit/javarosa/pull/515#issuecomment-565389703

As I said before, both classes are in very early stages, often with competing concepts and workflows. We hope that, by using them more, we will be able to figure out how they can serve us best. In that sense, every decision can be discussed and reviewed, so feel free to ask any question and give feedback about how it feels to use them.

**Comment by macdude357** [comment]
The test that is failing is not a stable test.  I looked into the issue and the way it is written, it will fail during certain times of the day (more so when run in a Timezone like PST that is 7-8 hours behind UTC).  I can look into fixing the test so it works all the time if you'd like.

Otherwise, the tests have all been migrated to JUnit 4.
@ggalmazor

**Comment by ggalmazor** [comment]
Thanks, @macdude357!! I'll be reviewing this now and we can decide what to do with that test later.

**Comment by lognaturel** [comment]
Thanks so much for doing this, @macdude357! Given your username, I'm surprised to see `^M` carriage returns in some places like https://github.com/opendatakit/javarosa/pull/514/files#diff-9bb5ac1af3332536b3bdf371f951261fR41! What did you use to edit?

**Comment by ggalmazor** [comment]
@macdude357, I've added a commit that fixes some line ending problems we've detected.

It turns out that some of your changes had a `\r` (carriage return) without a `\n` (new line), which was kinda weird. You normally have both if you're in Windows, or just `\n` if your on mac or *nix.

It was kind of tricky to solve this in a Linux box so, in case it's useful, here's what I did:

- First, make sure that your `core.autocrlf` git configuration is on `input`

  `git config --get core.autocrlf` tells you the local configuration value
  `git config --get --global core.autocrlf` tells you the value that will be used when cloning a repo for the first time
  `git config core.autocrlf input` sets it to `input. Add `--global` if you want to save it for future clonings

- Clone the repo, check the branch out, etc.
- Find offending files with `grep -l -r $'\r' src`

  The command reports:

  ```
  src/test/resources/hhplotdetails.csv
  src/test/java/org/javarosa/core/io/test/BufferedInputStreamTests.java
  src/test/java/org/javarosa/core/form/api/test/TextFormTests.java
  src/test/java/org/javarosa/core/model/Safe2014DagImplTest.java
  src/test/java/org/javarosa/core/model/instance/TreeReferenceParentTest.java
  src/test/java/org/javarosa/core/model/instance/test/QuestionDataGroupTests.java
  src/test/java/org/javarosa/core/model/instance/test/QuestionDataElementTests.java
  src/test/java/org/javarosa/core/model/instance/TreeReferenceAnchorHarnessTest.java
  src/test/java/org/javarosa/core/model/instance/TreeReferenceEqualsTest.java
  src/test/java/org/javarosa/core/model/SelectMultipleChoiceFilterTest.java
  src/test/java/org/javarosa/core/model/data/test/DateDataTests.java
  src/test/java/org/javarosa/core/model/data/test/StringDataTests.java
  src/test/java/org/javarosa/core/model/data/test/IntegerDataTests.java
  src/test/java/org/javarosa/core/model/data/test/TimeDataTests.java
  src/test/java/org/javarosa/core/model/data/test/TimeDataLimitationsTest.java
  src/test/java/org/javarosa/core/model/data/test/SelectOneDataTests.java
  src/test/java/org/javarosa/core/model/data/test/MultipleItemsDataTests.java
  src/test/java/org/javarosa/core/model/utils/test/LocalizerTest.java
  src/test/java/org/javarosa/core/model/SelectOneChoiceFilterTest.java
  src/test/java/org/javarosa/core/model/actions/MultipleEventsTest.java
  src/test/java/org/javarosa/core/model/condition/RecalculateTest.java
  src/test/java/org/javarosa/core/reference/ReferenceManagerTest.java
  src/test/java/org/javarosa/core/util/test/ExternalizableTest.java
  src/test/java/org/javarosa/core/util/test/NumericEncodingTest.java
  src/test/java/org/javarosa/xform/util/test/XFormAnswerDataSerializerTest.java
  ```

- Run `sed -i 's/\r/\n/g' {file}` for each one of them

**Pull request merged**
