### PR TITLE
PRs should have information to help with testing and docs

### PR DESCRIPTION
**Pull request by yanokwa**
This matches the questions we ask for Collect.
https://github.com/opendatakit/collect/blob/master/.github/PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by tiritea** [comment]
Somewhat related, do all javaRosa PR's require an github issue, or is referencing Forum feature request sufficient? There seems to be some duplication here, especially wrt approval new feature requests... should new features pass thru Forum Features first, then *after* 'approved' open a github issue (?). Then what should trigger submitting actual change PR?

Just for my future reference; I'm not sure what the correct procedure is (whatever it is, I'm sure I've violated it in some manner... :-)

**Comment by ggalmazor** [comment]
The only nuance here is that "users" are developers of other apps that import JavaRosa. I don't know how you feel about changing the language to address this difference.

**Comment by yanokwa** [comment]
@ggalmazor I appreciate your attention to detail here because it's the kind of think I would complain about 😂, but in this case I think it's fine.

@tiritea The official process is documented at https://github.com/opendatakit/governance/tree/master/TSC1#roadmapping. Our governance suggests (and I prefer) an issue that the PR is closing. We start on the forum to give non-devs who aren't on GitHub a chance to chime in. Once that discussion is done, then an issue is filed. Changes to JR doesn't always have a user-facing impact, but it might and so we want to give folks a chance to comment. Also, it's good practice.

I hear you that there is some duplication and it's a wee bit onerous, but I think the consistency of a process that works for most of the features we do outweighs the annoyance of creating an issue. If it's truly a barrier to contribution, then I'm open to tweaking it.

**Comment by tiritea** [comment]
No barrier, and I certainly wouldn't call cut-n-pasting a few lines of text from the Forum onerous... :-) I shalt endeavor to follow the official process in the future, thnx much.

**Pull request merged**
